name: Deploy to Heroku

on:
  pull_request:
    branches: [ development ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "beheersnakegame" #Must be unique in Heroku
          heroku_email: "janvandertuin@live.nl"
