name: CI
on:
  # Triggers the workflow on push or pull request events but only for the developmnent branch.
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# The jobs get executed paralell so they don't need eachother.
jobs:
  # This workflow contains a four jobs: build, test, lint, deploy.
  build:
    name: Build and install dependencies
    runs-on: ubuntu-latest
    defaults:
      # Change working directory, refactor needed in later issue.
      run:
        shell: bash
        working-directory: snakegame
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout master branch
        uses: actions/checkout@v2
      - name: Setting up NodeJS
        uses: actions/setup-node@master
      - name: installling Node dependencies
        run: npm install
      - name: Building node application
        run: npm run build
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: snakegame
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
      - name: Setting up NodeJS
        uses: actions/setup-node@master
      - name: installling Node dependencies
        run: npm install
      - name: Running unit tests
        run: npm run test:unit

   
