# This workflow executes unit tests located in the /tests folder on every pull request to the development branch
name: Unit testing
on:
  pull_request:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
      - name: Setting up NodeJS
        uses: actions/setup-node@master
      - name: installling Node dependencies
        run: npm install
      - name: Running unit tests
        run: npm run test:unit